---
language: node_js
node_js:
- 0.10.1
script:
- ./node_modules/grunt-cli/bin/grunt test
env:
  global:
    secure: |-
      SHezJGUSi1cc/V+AWBgmGe/SL1zPO4LC9baMGWyQJJetOexBJM/zIMR3J8Ci
      BJTr9VCK9CpBk00P+fAlXzPseQJtNjXNJjHsuN+3x/IHAhK2gn1gLwqvhIEI
      arzSh1mi64cfJP5kuJOGcJzjBwk6rI2ZNsiWxHYtAZA2g3R45eY=
